### ISSUE TITLE
Markdown doesn't load on search()

### ISSUE THREAD

**Issue by logan-jobzmall** [pubnub/chat-engine-markdown#4]
Exactly the same code and problem as on this ticket (except with the markdown plugin): https://github.com/pubnub/chat-engine-emoji/issues/1

`room.chat.plugin(ChatEngineCore.plugin['chat-engine-markdown']());`

**Comment by ianjennings** [comment]
As you figured in the other ticket, plugins need to be attached to search() as well. This will change in the future.
